{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}

kind: Pod
apiVersion: v1
metadata:
  name: {{ $release_name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    chart: "{{ $chart_name }}-{{ $chart_version }}"
    app: banana
spec:
  containers:
    - name:  {{ $release_name }}
      image: hashicorp/http-echo
      args:
        - "-text=banana"
